### ISSUE TITLE
Polling Stream

### ISSUE THREAD

**Issue by acabezas37** [atleon/atleon#20]
**Describe the feature**
We would like to have the ability to represent a generic polling model as a reactive stream. The end user could create their own specific implementation of a poller (including offsetting) and configure the polling interval used to access the resource.

**Rational**
There are occasionally situations where a user may need to poll an external resource periodically for changes and would like to be able to process these changes as events in a stream.

**Example Scenario**
A service keeps track of the state of certain domain entities and exposes an endpoint where you can fetch all state changes for a provided start/end. In this case we would want to be able to represent a periodic polling of that endpoint with a moving window as a bursty stream for processing.

**Comment by Sage-Pierce** [comment]
Completed via #21
